using Lidstroem.Core.Entities.Base;

namespace Lidstroem.Core.Auth;

/// <summary>
/// A short-lived one-time token used to let a user set their own password
/// without requiring an email service. The token is generated by a SuperAdmin
/// and shared out-of-band (copy-paste, Slack, etc.).
/// </summary>
public class PasswordResetToken : BaseEntity
{
    public int ActorId { get; set; }

    /// <summary>URL-safe base64 random token (43 chars, no padding).</summary>
    public string Token { get; set; } = string.Empty;

    public DateTime ExpiresAt { get; set; }
    public bool IsUsed { get; set; }
    public DateTime? UsedAt { get; set; }
}
